let data = [
  {
    name: "Mutton Biryani",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/06/Mutton-Biryani-Recipe.jpg",
    price1: 125,
    price2:230,
    off: 17,
    like: 44,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 70,
  },
  {
    name: "Tawa Paneer",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2023/12/Tawa-Paneer-Masala-1-1024x1534.jpg",
    price1: 120,
    price2:230,
    off: 32,
    like: 55,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 40,
  },
  {
    name: "Chicken Biryani",
    url: "https://www.licious.in/blog/wp-content/uploads/2022/06/chicken-hyderabadi-biryani-01.jpg",
    price1: 150,
    price2: 300,
    off: 20,
    like: 66,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Tandori",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2022/12/Tandoori-Chicken-1-1024x1534.jpg",
    price1: 100,
    price2: 180,
    off: 25,
    like: 77,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 60,
  },
  {
    name: "Butter Chicken",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2018/01/Butter-Chicken670.jpg",
    price1: 120,
    price2: 220,
    off: 30,
    like: 88,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Curry",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2023/11/Methi-Chicken-3-1024x1534.jpg",
    price1: 140,
    price2: 250,
    off: 35,
    like: 99,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 50,
  },
];
export default data;