let data = [
  {
    name: "Mutton Biryani",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2020/06/Mutton-Biryani-Recipe.jpg",
    price1: 125,
    price2: 230,
    off: 17,
    like: 44,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 70,
  },
  {
    name: "Tawa Paneer",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2023/12/Tawa-Paneer-Masala-1-1024x1534.jpg",
    price1: 120,
    price2: 230,
    off: 32,
    like: 55,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 40,
  },
  {
    name: "Chicken Biryani",
    url: "https://www.licious.in/blog/wp-content/uploads/2022/06/chicken-hyderabadi-biryani-01.jpg",
    price1: 150,
    price2: 300,
    off: 20,
    like: 66,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Tandori",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2022/12/Tandoori-Chicken-1-1024x1534.jpg",
    price1: 100,
    price2: 180,
    off: 25,
    like: 77,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 60,
  },
  {
    name: "Butter Chicken",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2018/01/Butter-Chicken670.jpg",
    price1: 120,
    price2: 220,
    off: 30,
    like: 88,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Curry",
    url: "https://www.cubesnjuliennes.com/wp-content/uploads/2023/11/Methi-Chicken-3-1024x1534.jpg",
    price1: 140,
    price2: 250,
    off: 35,
    like: 99,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 50,
  },
  {
    name: "Panir Tikka",
    url: "https://www.indianveggiedelight.com/wp-content/uploads/2021/08/air-fryer-paneer-tikka-1152x1536.jpg",
    price1: 110,
    price2: 200,
    off: 33,
    like: 82,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 60,
  },
  {
    name: "Manchurian",
    url: "https://b2958125.smushcdn.com/2958125/wp-content/uploads/chicken-manchurian-recipe-dry-restaurant-style-1.jpg?lossy=1&strip=1&webp=1",
    price1: 60,
    price2: 120,
    off: 39,
    like: 20,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Green Chicken",
    url: "https://myheartbeets.com/wp-content/uploads/2020/02/hariyali-chicken.jpg",
    price1: 80,
    price2: 160,
    off: 89,
    like: 24,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Kabab",
    url: "https://myheartbeets.com/wp-content/uploads/2021/11/easy-chicken-kebabs-392x392.jpg",
    price1: 110,
    price2: 2000,
    off: 21,
    like: 90,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Turkey Biryani",
    url: "https://myheartbeets.com/wp-content/uploads/2020/11/Turkey-Biriyani-instant-pot-392x392.jpg",
    price1: 60,
    price2: 120,
    off: 29,
    like: 60,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Vindaloo",
    url: "https://myheartbeets.com/wp-content/uploads/2020/03/instant-pot-chicken-vindaloo-392x392.jpg",
    price1: 70,
    price2: 130,
    off: 31,
    like: 90,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Chicken Saag",
    url: "https://myheartbeets.com/wp-content/uploads/2019/10/instant-pot-palak-chicken-392x392.jpg",
    price1: 90,
    price2: 160,
    off: 20,
    like: 95,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
  {
    name: "Kofta Curry",
    url: "https://myheartbeets.com/wp-content/uploads/2019/09/Kofta-Curry-ground-meat-beef-lamb-392x392.jpg",
    price1: 75,
    price2: 140,
    off: 31,
    like: 40,
    islike: false,
    surcharge: 0,
    service: 0,
    total: 0,
    deliveryFees: 30,
  },
];
export default data;